[package]
name = "server090"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-modbus = "0.9.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] } 
anyhow = "1.0.75"